getProject and getPhase API.
NPNKhoa/CT240-frontend pull request #7
Opened 2024-10-30 02:55 UTC by MPhus

2024-10-30 03:29 UTC, NPNKhoa requested changes
- Lúc tạo project thì cho endDate là optional (đã sửa ở BE)

![image](https://github.com/user-attachments/assets/c5db69c9-7bc3-45b4-aba7-0c5ff39fba54)

- Tạo project hong đc

![image](https://github.com/user-attachments/assets/be3e5e01-efcd-4a48-9e35-1b646311d646)


- Delete cũng k đc

![image](https://github.com/user-attachments/assets/1871784e-9a5c-4ee9-a8ff-179910a62fe6)

- Thêm token vào các request
- Chỉnh sửa UI cho project detail (cho cái status nó có màu màu tí, theo 3 trạng thái active, complete, canceled tương ứng màu xanh dương, xanh lá, đỏ)

2024-10-30 03:32 UTC, MPhus commented
ông pull cái commit mới nhất chưa á, cái delêt với ui để tui check lại, create tui mới fix á

2024-11-01 14:31 UTC, NPNKhoa requested changes
- Tạo phase nhưng mà thông báo "create project successfully"
![image](https://github.com/user-attachments/assets/0c7269b3-afe2-46ce-9735-bfe98fe6f3c0)

- create phase xong ròi mở cái này lên để create cái mới mà nó vẫn lưu thông tin cữ
![image](https://github.com/user-attachments/assets/f6387885-be22-4848-9697-1129b753a796)

- bug tooooo, tạo 1 mà ra 2 nè :)))
![image](https://github.com/user-attachments/assets/cce21408-fbef-44c4-8ad2-14d1047d12b7)

- create project xong nên nhảy tới cái project đó nha, hiện tại đang bị trắng trang
![image](https://github.com/user-attachments/assets/168c7c96-5bb6-4999-82f5-6830a075350b)

2024-11-03 06:18 UTC, NPNKhoa approved these changes

2024-11-03 06:19 UTC, merged